# Generated by cucumber-sinatra. (2014-09-18 14:28:57 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'server.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = GoodbyeAlex

class GoodbyeAlexWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  GoodbyeAlexWorld.new
end
